name: CI/CD for simple-http-checker

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Display Python version and location
        run: |
          python --version
          which python
      - name: Install dev dependencies
        run: pip install ".[dev]"
      - name: Run Format checks with Black
        run: black --check . --target-version py312
      - name: Run linting checks with Ruff
        run: ruff check .